main.obj
owo.js_plugin_import.obj
owo.js_qml_plugin_import.obj
qrc_qmake_resources.obj
C:/Qt/6.4.2/wasm_32/lib/objects-Release/QWasmIntegrationPlugin_resources_1/.rcc/qrc_wasmfonts.cpp.o
C:/Qt/6.4.2/wasm_32/lib/objects-Release/Gui_resources_1/.rcc/qrc_qpdf.cpp.o
C:/Qt/6.4.2/wasm_32/lib/objects-Release/Gui_resources_2/.rcc/qrc_gui_shaders.cpp.o
C:/Qt/6.4.2/wasm_32/plugins/platforms/libqwasm.a
C:/Qt/6.4.2/wasm_32/plugins/iconengines/libqsvgicon.a
C:/Qt/6.4.2/wasm_32/plugins/imageformats/libqgif.a
C:/Qt/6.4.2/wasm_32/plugins/imageformats/libqicns.a
C:/Qt/6.4.2/wasm_32/plugins/imageformats/libqico.a
C:/Qt/6.4.2/wasm_32/plugins/imageformats/libqjpeg.a
C:/Qt/6.4.2/wasm_32/lib/libQt6BundledLibjpeg.a
C:/Qt/6.4.2/wasm_32/plugins/imageformats/libqsvg.a
C:/Qt/6.4.2/wasm_32/lib/libQt6Svg.a
C:/Qt/6.4.2/wasm_32/plugins/imageformats/libqtga.a
C:/Qt/6.4.2/wasm_32/plugins/imageformats/libqtiff.a
C:/Qt/6.4.2/wasm_32/plugins/imageformats/libqwbmp.a
C:/Qt/6.4.2/wasm_32/plugins/imageformats/libqwebp.a
C:/Qt/6.4.2/wasm_32/plugins/tls/libqcertonlybackend.a
C:/Qt/6.4.2/wasm_32/./qml/QtQuick/objects-Release/Quick_resources_1/.rcc/qrc_qmake_QtQuick.cpp.o
C:/Qt/6.4.2/wasm_32/lib/objects-Release/Quick_resources_2/.rcc/qrc_scenegraph_shaders.cpp.o
C:/Qt/6.4.2/wasm_32/./qml/QtQml/Models/objects-Release/QmlModels_resources_1/.rcc/qrc_qmake_QtQml_Models.cpp.o
C:/Qt/6.4.2/wasm_32/./qml/QtQml/objects-Release/Qml_resources_1/.rcc/qrc_qmake_QtQml.cpp.o
C:/Qt/6.4.2/wasm_32/qml/QtQuick/libqtquick2plugin.a
C:/Qt/6.4.2/wasm_32/lib/libQt6Quick.a
C:/Qt/6.4.2/wasm_32/lib/libQt6OpenGL.a
C:/Qt/6.4.2/wasm_32/lib/libQt6Gui.a
C:/Qt/6.4.2/wasm_32/lib/libQt6BundledHarfbuzz.a
C:/Qt/6.4.2/wasm_32/lib/libQt6BundledFreetype.a
C:/Qt/6.4.2/wasm_32/lib/libQt6BundledLibpng.a
C:/Qt/6.4.2/wasm_32/qml/QtQml/libqmlplugin.a
C:/Qt/6.4.2/wasm_32/qml/QtQml/Models/libmodelsplugin.a
C:/Qt/6.4.2/wasm_32/lib/libQt6QmlModels.a
C:/Qt/6.4.2/wasm_32/lib/libQt6Qml.a
C:/Qt/6.4.2/wasm_32/lib/libQt6Network.a
C:/Qt/6.4.2/wasm_32/lib/libQt6Core.a
C:/Qt/6.4.2/wasm_32/lib/libQt6BundledZLIB.a
C:/Qt/6.4.2/wasm_32/lib/libQt6BundledPcre2.a
-lembind
